var data = [
  {
    name: "A",
    type: "letter",
    img: "photos/a.png",
    audio: "audios/a.mp3",
  },
  {
    name: "B",
    type: "letter",
    img: "photos/b.png",
    audio: "audios/b.mp3",
  },
  {
    name: "C",
    type: "letter",
    img: "photos/c.png",
    audio: "audios/c.mp3",
  },
  {
    name: "D",
    type: "letter",
    img: "photos/d.png",
    audio: "audios/d.mp3",
  },
  {
    name: "E",
    type: "letter",
    img: "photos/e.png",
    audio: "audios/e.mp3",
  },
  {
    name: "F",
    type: "letter",
    img: "photos/f.png",
    audio: "audios/f.mp3",
  },
  {
    name: "G",
    type: "letter",
    img: "photos/g.png",
    audio: "audios/g.mp3",
  },
  {
    name: "H",
    type: "letter",
    img: "photos/h.png",
    audio: "audios/h.mp3",
  },
  {
    name: "I",
    type: "letter",
    img: "photos/i.png",
    audio: "audios/i.mp3",
  },
  {
    name: "J",
    type: "letter",
    img: "photos/j.png",
    audio: "audios/j.mp3",
  },
  {
    name: "K",
    type: "letter",
    img: "photos/k.png",
    audio: "audios/k.mp3",
  },
  {
    name: "L",
    type: "letter",
    img: "photos/l.png",
    audio: "audios/l.mp3",
  },
  {
    name: "M",
    type: "letter",
    img: "photos/m.png",
    audio: "audios/m.mp3",
  },
  {
    name: "N",
    type: "letter",
    img: "photos/n.png",
    audio: "audios/n.mp3",
  },
  {
    name: "O",
    type: "letter",
    img: "photos/o.png",
    audio: "audios/o.mp3",
  },
  {
    name: "P",
    type: "letter",
    img: "photos/p.png",
    audio: "audios/p.mp3",
  },
  {
    name: "Q",
    type: "letter",
    img: "photos/q.png",
    audio: "audios/q.mp3",
  },
  {
    name: "R",
    type: "letter",
    img: "photos/r.png",
    audio: "audios/r.mp3",
  },
  {
    name: "S",
    type: "letter",
    img: "photos/s.png",
    audio: "audios/s.mp3",
  },

  {
    name: "T",
    type: "letter",
    img: "photos/t.png",
    audio: "audios/t.mp3",
  },
  {
    name: "U",
    type: "letter",
    img: "photos/u.png",
    audio: "audios/u.mp3",
  },
  {
    name: "V",
    type: "letter",
    img: "photos/v.png",
    audio: "audios/v.mp3",
  },
  {
    name: "W",
    type: "letter",
    img: "photos/w.png",
    audio: "audios/w.mp3",
  },
  {
    name: "X",
    type: "letter",
    img: "photos/x.png",
    audio: "audios/x.mp3",
  },
  {
    name: "Y",
    type: "letter",
    img: "photos/y.png",
    audio: "audios/y.mp3",
  },
  {
    name: "Z",
    type: "letter",
    img: "photos/z.png",
    audio: "audios/z.mp3",
  },
  //  animals
  {
    name: "dog",
    type: "animal",
    img: "photos/dog.jpg",
    audio: "audios/dog.M4A",
  },
  {
    name: "cat",
    type: "animal",
    img: "photos/cat.jpg",
    audio: "audios/cat.M4A",
  },
  {
    name: "horse",
    type: "animal",
    img: "photos/horse.jpg",
    audio: "audios/horse.M4A",
  },
  {
    name: "lion",
    type: "animal",
    img: "photos/lion.jpg",
    audio: "audios/lion.M4A",
  },
  {
    name: "frog",
    type: "animal",
    img: "photos/frog.jpg",
    audio: "audios/frog.M4A",
  },
  {
    name: "bear",
    type: "animal",
    img: "photos/bear.jpg",
    audio: "audios/bear.M4A",
  },
  {
    name: "elephant",
    type: "animal",
    img: "photos/elephant.jpg",
    audio: "audios/elephant.M4A",
  },
  {
    name: "cow",
    type: "animal",
    img: "photos/cow.jpg",
    audio: "audios/cow.M4A",
  },
  {
    name: "sheep",
    type: "animal",
    img: "photos/sheep.jpg",
    audio: "audios/sheep.M4A",
  },
  {
    name: "goats",
    type: "animal",
    img: "photos/goats.jpg",
    audio: "audios/goats.M4A",
  },
  {
    name: "mouse",
    type: "animal",
    img: "photos/mouse.jpg",
    audio: "audios/mouse.M4A",
  },
  {
    name: "owl",
    type: "animal",
    img: "photos/owl.jpg",
    audio: "audios/owl.M4A",
  },
  // numbers
  {
    name: "1",
    type: "number",
    img: "photos/1.png",
    audio: "audios/1.mp3",
  },
  {
    name: "2",
    type: "number",
    img: "photos/2.png",
    audio: "audios/2.mp3",
  },
  {
    name: "3",
    type: "number",
    img: "photos/3.png",
    audio: "audios/3.mp3",
  },
  {
    name: "4",
    type: "number",
    img: "photos/4.png",
    audio: "audios/4.mp3",
  },
  {
    name: "5",
    type: "number",
    img: "photos/5.png",
    audio: "audios/5.mp3",
  },
  {
    name: "6",
    type: "number",
    img: "photos/6.png",
    audio: "audios/6.mp3",
  },
  {
    name: "7",
    type: "number",
    img: "photos/7.png",
    audio: "audios/7.mp3",
  },
  {
    name: "8",
    type: "number",
    img: "photos/8.png",
    audio: "audios/8.mp3",
  },
  {
    name: "9",
    type: "number",
    img: "photos/9.png",
    audio: "audios/9.mp3",
  },

  {
    name: "10",
    type: "number",
    img: "photos/10.png",
    audio: "audios/10.mp3",
  },
];
